language: minimal
dist: focal
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
  - sudo pip install codecov
script:
  - docker build -t vtkbool_coverage -f Dockerfile.archlinux .
  - id=$(docker run -t -d vtkbool_coverage)
  - docker cp $id:/refactoring/build/coverage.xml .
  - docker stop -t 0 $id
  - codecov
  - docker build -t vtkbool_release -f Dockerfile.ubuntu .
