FROM ubuntu:latest
RUN apt-get update
RUN apt-get -y upgrade
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN apt-get -y install libvtk9-dev python3-vtk9 cmake python3-pytest
WORKDIR /refactoring
COPY . .
RUN ls -alh
WORKDIR /refactoring/build
RUN cmake -DCMAKE_BUILD_TYPE=RELEASE ..
RUN make
RUN ctest --output-on-failure
