name: CMake

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]
        cxx: [g++, clang++]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Install Deps
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
        sudo apt-get -y install libvtk9-dev python3-vtk9 python3-pytest

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      env:
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure -C ${{matrix.build_type}}

  Coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Deps
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
        sudo apt-get -y install libvtk9-dev python3-vtk9 python3-pytest gcovr

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Profile -DVTKBOOL_COVERAGE=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ctest --output-on-failure
        gcovr -r .. . --exclude-throw-branches --xml -o coverage.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}

